//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CalendarDetail
    {
        public int CalendarDetailId { get; set; }
        public string CalendarDetailName { get; set; }
        public int ParentCalendarId { get; set; }
        public int CalendarId { get; set; }
        public int Sequence { get; set; }
        public Nullable<int> Priority { get; set; }
        public Nullable<int> Interval { get; set; }
        public string Value { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public byte[] VersionStamp { get; set; }
    
        public virtual Calendar Calendar { get; set; }
        public virtual Calendar Calendar1 { get; set; }
    }
}
