//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CustomerItem
    {
        public int CustomerItemID { get; set; }
        public string CustomerItemName { get; set; }
        public int CustomerID { get; set; }
        public int ItemID { get; set; }
        public Nullable<int> ParentItemID { get; set; }
        public Nullable<decimal> UnitPrice { get; set; }
        public Nullable<int> InternalTAT { get; set; }
        public Nullable<int> ExternalTAT { get; set; }
        public Nullable<int> PriceUomID { get; set; }
        public string String1 { get; set; }
        public string String2 { get; set; }
        public string String3 { get; set; }
        public string String4 { get; set; }
        public string String5 { get; set; }
        public string String6 { get; set; }
        public string String7 { get; set; }
        public string String8 { get; set; }
        public string MaxString1 { get; set; }
        public string MaxString2 { get; set; }
        public string MaxString3 { get; set; }
        public Nullable<int> Int1 { get; set; }
        public Nullable<int> Int2 { get; set; }
        public Nullable<decimal> Int3 { get; set; }
        public Nullable<int> Int4 { get; set; }
        public Nullable<double> Float1 { get; set; }
        public Nullable<double> Float2 { get; set; }
        public Nullable<bool> Flag1 { get; set; }
        public Nullable<bool> Flag2 { get; set; }
        public Nullable<bool> Flag3 { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public byte[] VersionStamp { get; set; }
    
        public virtual Customer Customer { get; set; }
        public virtual Item Item { get; set; }
    }
}
