//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SIMAPS_MOM : DbContext
    {
        //public SIMAPS_MOM()
        //    : base("name=SIMAPS_MOM")
        //{
        //}

        //constructor
        public SIMAPS_MOM() : base(GetConnString())
        { }

        //methods
        private static string GetConnString()
        {
            var conn = new ConnectionStringFactory1();
            return conn.GetTestDBConnection1();
        }
        public override int SaveChanges()
        {
            ChangeTracker.DetectChanges();
            DbContextSaveChanges.SaveChanges(((IObjectContextAdapter)this).ObjectContext);

            return base.SaveChanges();
        }

        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<InvMa> InvMas { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<CapacityProfile> CapacityProfiles { get; set; }
        public virtual DbSet<DailyLoadingPlan> DailyLoadingPlans { get; set; }
        public virtual DbSet<OrderRelease> OrderReleases { get; set; }
        public virtual DbSet<OrderReleaseDetail> OrderReleaseDetails { get; set; }
        public virtual DbSet<Schedule> Schedules { get; set; }
        public virtual DbSet<ScheduleDetail> ScheduleDetails { get; set; }
        public virtual DbSet<ctr_mc> ctr_mc { get; set; }
        public virtual DbSet<part_detail_semicon> part_detail_semicon { get; set; }
        public virtual DbSet<PPOrder> PPOrders { get; set; }
        public virtual DbSet<PPOrderDetail> PPOrderDetails { get; set; }
        public virtual DbSet<PPOrderRoute> PPOrderRoutes { get; set; }
        public virtual DbSet<Right> Rights { get; set; }
        public virtual DbSet<RouteMa> RouteMas { get; set; }
        public virtual DbSet<SalesOrderCancelDet> SalesOrderCancelDets { get; set; }
        public virtual DbSet<SalesOrderCancelled> SalesOrderCancelleds { get; set; }
        public virtual DbSet<shift_det> shift_det { get; set; }
        public virtual DbSet<user_det> user_det { get; set; }
        public virtual DbSet<working_Rate_except> working_Rate_except { get; set; }
        public virtual DbSet<WorkOrderAssembly> WorkOrderAssemblies { get; set; }
        public virtual DbSet<WorkorderMac> WorkorderMacs { get; set; }
        public virtual DbSet<WorkOrderMaster> WorkOrderMasters { get; set; }
        public virtual DbSet<WorkOrderMaterial> WorkOrderMaterials { get; set; }
        public virtual DbSet<Inventory> Inventories { get; set; }
        public virtual DbSet<InventoryUsage> InventoryUsages { get; set; }
        public virtual DbSet<Customer> Customers { get; set; }
        public virtual DbSet<DeliveryOrder> DeliveryOrders { get; set; }
        public virtual DbSet<DeliveryOrderDetail> DeliveryOrderDetails { get; set; }
        public virtual DbSet<SalesOrder> SalesOrders { get; set; }
        public virtual DbSet<SalesOrderAdjustment> SalesOrderAdjustments { get; set; }
        public virtual DbSet<SalesOrderDetail> SalesOrderDetails { get; set; }
        public virtual DbSet<WorkOrder> WorkOrders { get; set; }
        public virtual DbSet<WorkOrderAdjustment> WorkOrderAdjustments { get; set; }
        public virtual DbSet<WorkOrderCost> WorkOrderCosts { get; set; }
        public virtual DbSet<WorkOrderDetail> WorkOrderDetails { get; set; }
        public virtual DbSet<WorkOrderMaterial1> WorkOrderMaterial1 { get; set; }
        public virtual DbSet<Operation> Operations { get; set; }
        public virtual DbSet<OperationParameter> OperationParameters { get; set; }
        public virtual DbSet<OperationRate> OperationRates { get; set; }
        public virtual DbSet<OperationResource> OperationResources { get; set; }
        public virtual DbSet<Parameter> Parameters { get; set; }
        public virtual DbSet<ProductRoute> ProductRoutes { get; set; }
        public virtual DbSet<ProductRouteStatu> ProductRouteStatus { get; set; }
        public virtual DbSet<Route> Routes { get; set; }
        public virtual DbSet<RouteOperation> RouteOperations { get; set; }
        public virtual DbSet<BillOfMaterial> BillOfMaterials { get; set; }
        public virtual DbSet<CustomerItem> CustomerItems { get; set; }
        public virtual DbSet<Item> Items { get; set; }
        public virtual DbSet<ItemLocation> ItemLocations { get; set; }
        public virtual DbSet<Location> Locations { get; set; }
        public virtual DbSet<Picture> Pictures { get; set; }
        public virtual DbSet<UserProductLine> UserProductLines { get; set; }
        public virtual DbSet<Calendar> Calendars { get; set; }
        public virtual DbSet<CalendarDetail> CalendarDetails { get; set; }
        public virtual DbSet<Equipment> Equipments { get; set; }
        public virtual DbSet<EquipmentParameter> EquipmentParameters { get; set; }
        public virtual DbSet<Button> Buttons { get; set; }
        public virtual DbSet<Menu> Menus { get; set; }
        public virtual DbSet<Role> Roles { get; set; }
        public virtual DbSet<RoleTask> RoleTasks { get; set; }
        public virtual DbSet<Task> Tasks { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<UserRole> UserRoles { get; set; }
        public virtual DbSet<CodeDetail> CodeDetails { get; set; }
        public virtual DbSet<CodeType> CodeTypes { get; set; }
        public virtual DbSet<CodeUsage> CodeUsages { get; set; }
        public virtual DbSet<Option> Options { get; set; }
        public virtual DbSet<UserPreference> UserPreferences { get; set; }
        public virtual DbSet<tmpRoute> tmpRoutes { get; set; }
        public virtual DbSet<ctr_mc1> ctr_mc1 { get; set; }
        public virtual DbSet<Customer1> Customer1 { get; set; }
        public virtual DbSet<OperatorAssg> OperatorAssgs { get; set; }
        public virtual DbSet<part_detail_semicon1> part_detail_semicon1 { get; set; }
        public virtual DbSet<PPOrder1> PPOrder1 { get; set; }
        public virtual DbSet<PPOrderDetail1> PPOrderDetail1 { get; set; }
        public virtual DbSet<PPOrderRoute1> PPOrderRoute1 { get; set; }
        public virtual DbSet<product_leadtime> product_leadtime { get; set; }
        public virtual DbSet<product_working_rate> product_working_rate { get; set; }
        public virtual DbSet<RouteDet> RouteDets { get; set; }
        public virtual DbSet<RouteDetAll> RouteDetAlls { get; set; }
        public virtual DbSet<RouteMas1> RouteMas1 { get; set; }
        public virtual DbSet<shift_det1> shift_det1 { get; set; }
        public virtual DbSet<TM_Rights> TM_Rights { get; set; }
        public virtual DbSet<unit_det> unit_det { get; set; }
        public virtual DbSet<user_det1> user_det1 { get; set; }
        public virtual DbSet<View_TS_WOAdjustment> View_TS_WOAdjustment { get; set; }
        public virtual DbSet<View_TS_WorkOrder> View_TS_WorkOrder { get; set; }
        public virtual DbSet<working_rate_except1> working_rate_except1 { get; set; }
        public virtual DbSet<WorkOrderAssembly1> WorkOrderAssembly1 { get; set; }
        public virtual DbSet<WorkOrderInfo> WorkOrderInfoes { get; set; }
        public virtual DbSet<WorkOrderMac1> WorkOrderMac1 { get; set; }
        public virtual DbSet<WorkOrderMaster1> WorkOrderMaster1 { get; set; }
        public virtual DbSet<WorkOrderMaterial2> WorkOrderMaterial2 { get; set; }
    }
}
