//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class PPOrderDetail1
    {
        public int ID { get; set; }
        public Nullable<int> MeltingOrderID { get; set; }
        public Nullable<int> PPID { get; set; }
        public string PartNo { get; set; }
        public string SalesOrderID { get; set; }
        public Nullable<int> SalesOrderDetID { get; set; }
        public decimal Weight { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> EstCompletionDate { get; set; }
    }
}
