//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesOrderAdjustment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SalesOrderAdjustment()
        {
            this.WorkOrderAdjustments = new HashSet<WorkOrderAdjustment>();
        }
    
        public int SalesOrderAjustmentID { get; set; }
        public int SalesOrderDetailID { get; set; }
        public Nullable<double> OrigianlQty { get; set; }
        public Nullable<double> PlannedQty { get; set; }
        public Nullable<double> ReducedQty { get; set; }
        public Nullable<double> BalanceQty { get; set; }
        public string Remark { get; set; }
        public Nullable<int> Status { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public byte[] VersionStamp { get; set; }
    
        public virtual SalesOrderDetail SalesOrderDetail { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderAdjustment> WorkOrderAdjustments { get; set; }
    }
}
