//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class TM_Rights
    {
        public string User_grp { get; set; }
        public string Unit_id { get; set; }
        public string Object_id { get; set; }
        public int Rights { get; set; }
        public string usergrp_flag { get; set; }
    }
}
