//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class tmpRoute
    {
        public int id { get; set; }
        public int RouteID { get; set; }
        public int OperationID { get; set; }
        public Nullable<int> Subrouteid { get; set; }
        public int Sequence { get; set; }
        public Nullable<int> SubrouteSeq { get; set; }
    }
}
