//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class unit_det
    {
        public string LocationName { get; set; }
        public string Description { get; set; }
        public Nullable<int> PictureID { get; set; }
        public byte[] ThumbNailImage { get; set; }
    }
}
