//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderAssembly1
    {
        public string ComponentWO { get; set; }
        public string AssyWO { get; set; }
        public double AssyQty { get; set; }
        public double ComponentQty { get; set; }
        public int QtyPer { get; set; }
        public Nullable<int> level { get; set; }
    }
}
