//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public WorkOrder()
        {
            this.DeliveryOrderDetails = new HashSet<DeliveryOrderDetail>();
            this.WorkOrderDetails = new HashSet<WorkOrderDetail>();
            this.WorkOrderMaterial1 = new HashSet<WorkOrderMaterial1>();
        }
    
        public int WorkOrderID { get; set; }
        public string WorkOrderNumber { get; set; }
        public int ProductID { get; set; }
        public double Quantity { get; set; }
        public byte OrderType { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public Nullable<short> Priority { get; set; }
        public Nullable<int> ParentWorkOrderID { get; set; }
        public byte Status { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<int> CustomerID { get; set; }
        public Nullable<int> RouteID { get; set; }
        public string Remarks { get; set; }
        public string String1 { get; set; }
        public string String2 { get; set; }
        public string String3 { get; set; }
        public string String4 { get; set; }
        public string String5 { get; set; }
        public string String6 { get; set; }
        public string String7 { get; set; }
        public string String8 { get; set; }
        public string MaxString1 { get; set; }
        public string MaxString2 { get; set; }
        public Nullable<int> Int1 { get; set; }
        public Nullable<int> Int2 { get; set; }
        public Nullable<int> Int3 { get; set; }
        public Nullable<int> Int4 { get; set; }
        public Nullable<int> Int5 { get; set; }
        public Nullable<int> Int6 { get; set; }
        public Nullable<double> Float1 { get; set; }
        public Nullable<double> Float2 { get; set; }
        public Nullable<System.DateTime> Date1 { get; set; }
        public Nullable<System.DateTime> Date2 { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public byte[] VersionStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DeliveryOrderDetail> DeliveryOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderDetail> WorkOrderDetails { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<WorkOrderMaterial1> WorkOrderMaterial1 { get; set; }
        public virtual Item Item { get; set; }
        public virtual Route Route { get; set; }
    }
}
