//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_Parameter
    {
        public int Threshold { get; set; }
        public Nullable<decimal> QCCheck { get; set; }
        public Nullable<decimal> SRPTThreshold { get; set; }
        public Nullable<decimal> EDDThreshold { get; set; }
        public Nullable<decimal> WOStatusThreshold { get; set; }
    }
}
