//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_Rework
    {
        public string WOID { get; set; }
        public string WorkCenter { get; set; }
        public int RouteID { get; set; }
        public int OpSeq { get; set; }
        public int ProcOpSeq { get; set; }
        public int ReworkRouteID { get; set; }
        public string ReworkStartWC { get; set; }
        public int ReworkStartOpSeq { get; set; }
        public int ReworkStartProcOpSeq { get; set; }
        public int ReworkQty { get; set; }
        public System.DateTime ReworkDate { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }
        public string RouteName { get; set; }
        public string AlertStatus { get; set; }
        public string ProblemWC { get; set; }
        public Nullable<int> ProblemOpSeq { get; set; }
        public Nullable<int> ProblemProcOpSeq { get; set; }
        public string ProblemOperatorID { get; set; }
        public string ProblemOperatorName { get; set; }
        public string ApprovedID { get; set; }
        public string ApprovedName { get; set; }
    
        public virtual TS_WorkOrder TS_WorkOrder { get; set; }
    }
}
