//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_WorkOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TS_WorkOrder()
        {
            this.TS_QC_Equipment = new HashSet<TS_QC_Equipment>();
            this.TS_Rework = new HashSet<TS_Rework>();
            this.TS_Scrap = new HashSet<TS_Scrap>();
            this.TS_Operation = new HashSet<TS_Operation>();
            this.TS_WorkOrderRoute = new HashSet<TS_WorkOrderRoute>();
            this.TS_WorkOrderExecution = new HashSet<TS_WorkOrderExecution>();
        }
    
        public string WOID { get; set; }
        public string PartID { get; set; }
        public System.DateTime RequestedDeliveryDate { get; set; }
        public System.DateTime CommittedDeliveryDate { get; set; }
        public int ReleasedProdQty { get; set; }
        public System.DateTime ReleasedProdDate { get; set; }
        public int ActualProdQty { get; set; }
        public System.DateTime ActualProdDate { get; set; }
        public int ActualRecQty { get; set; }
        public System.DateTime ActualRecDate { get; set; }
        public Nullable<int> CompletedQty { get; set; }
        public Nullable<System.DateTime> CompletedDate { get; set; }
        public int OutstandingQty { get; set; }
        public System.DateTime OutstandingDate { get; set; }
        public Nullable<int> AccumulatedScrapQty { get; set; }
        public Nullable<System.DateTime> AccumulatedScrapDate { get; set; }
        public Nullable<int> TotalActAdjustedQty { get; set; }
        public Nullable<System.DateTime> TotalActAdjustedDate { get; set; }
        public string WOStatus { get; set; }
        public string ToolDescription { get; set; }
        public string PlannerRemark { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string ParentWOID { get; set; }
        public string Remark { get; set; }
        public int PPID { get; set; }
        public string SalesOrderID { get; set; }
        public Nullable<System.DateTime> ReleasedDate { get; set; }
        public string AlertStatus { get; set; }
        public string OrderType { get; set; }
        public string OperatorID { get; set; }
        public string OperatorName { get; set; }
        public string ApprovedID { get; set; }
        public string ApprovedName { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_QC_Equipment> TS_QC_Equipment { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_Rework> TS_Rework { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_Scrap> TS_Scrap { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_Operation> TS_Operation { get; set; }
        public virtual TS_WorkOrderCancel TS_WorkOrderCancel { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_WorkOrderRoute> TS_WorkOrderRoute { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<TS_WorkOrderExecution> TS_WorkOrderExecution { get; set; }
    }
}
