//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_WorkOrderCancelDetail
    {
        public string WOID { get; set; }
        public string PartID { get; set; }
        public string WorkCenter { get; set; }
        public int RouteID { get; set; }
        public int OpSeq { get; set; }
        public int ProcOpSeq { get; set; }
        public int ActualAdjustQty { get; set; }
        public System.DateTime ActualAdjustDate { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
    }
}
