//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class CapacityProfile
    {
        public int OrderCapacityID { get; set; }
        public int ReleaseID { get; set; }
        public int OperationID { get; set; }
        public Nullable<int> OperationSequence { get; set; }
        public int ResourceID { get; set; }
        public Nullable<double> UsedRatio { get; set; }
        public double ProducedQuantity { get; set; }
        public System.DateTime ProductionDate { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public byte[] VersionStamp { get; set; }
    
        public virtual OrderRelease OrderRelease { get; set; }
    }
}
