//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Customer1
    {
        public int CustomerID { get; set; }
        public string cust_id { get; set; }
        public string Category { get; set; }
        public Nullable<int> Priority { get; set; }
        public string CompanyName { get; set; }
        public string Address { get; set; }
        public string BillingAddress { get; set; }
        public string ContactPerson { get; set; }
        public string Phone { get; set; }
        public string Email { get; set; }
        public Nullable<int> PictureID { get; set; }
    }
}
