//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class InventoryUsage
    {
        public int InventoryUsageID { get; set; }
        public int InventoryID { get; set; }
        public int UsageType { get; set; }
        public int UsedByOrderID { get; set; }
        public decimal Quantity { get; set; }
        public System.DateTime DateOut { get; set; }
        public string Status { get; set; }
        public string Remarks { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public byte[] VersionStamp { get; set; }
    
        public virtual Inventory Inventory { get; set; }
    }
}
