//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvMa
    {
        public int ID { get; set; }
        public string Location { get; set; }
        public System.DateTime DateIn { get; set; }
        public string InvType { get; set; }
        public string PartNo { get; set; }
        public string WorkOrder { get; set; }
        public string SubWorkOrder { get; set; }
        public string ReservedWorkOrder { get; set; }
        public Nullable<int> SeqNo { get; set; }
        public string CenterID { get; set; }
        public string Customer { get; set; }
        public int Qty { get; set; }
        public int BalQty { get; set; }
        public string Remarks { get; set; }
        public string Status { get; set; }
        public Nullable<decimal> ActualBalQty { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
    }
}
