//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class Operation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Operation()
        {
            this.OperationParameters = new HashSet<OperationParameter>();
            this.OperationResources = new HashSet<OperationResource>();
            this.RouteOperations = new HashSet<RouteOperation>();
        }
    
        public int OperationId { get; set; }
        public string OperationName { get; set; }
        public byte Type { get; set; }
        public string Categroy { get; set; }
        public string Description { get; set; }
        public string Instruction { get; set; }
        public Nullable<int> Version { get; set; }
        public Nullable<int> LocationID { get; set; }
        public Nullable<double> SizeMin { get; set; }
        public Nullable<double> SizeMultiple { get; set; }
        public Nullable<double> Cost { get; set; }
        public Nullable<double> Pretime { get; set; }
        public Nullable<double> Posttime { get; set; }
        public Nullable<double> Duration { get; set; }
        public Nullable<double> DurationPer { get; set; }
        public Nullable<int> UOM { get; set; }
        public bool IsActive { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public byte[] VersionStamp { get; set; }
    
        public virtual Location Location { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationParameter> OperationParameters { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OperationResource> OperationResources { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RouteOperation> RouteOperations { get; set; }
    }
}
