//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class OperationParameter
    {
        public int OperationParamterId { get; set; }
        public int OperationID { get; set; }
        public Nullable<int> ParamterID { get; set; }
        public string Value { get; set; }
        public string MinValue { get; set; }
        public string MaxValue { get; set; }
        public string UOM { get; set; }
        public Nullable<short> NoofReading { get; set; }
        public string MaxString1 { get; set; }
        public string MaxString2 { get; set; }
        public Nullable<int> Int1 { get; set; }
        public Nullable<int> Int2 { get; set; }
        public Nullable<int> Int3 { get; set; }
        public Nullable<int> Int4 { get; set; }
        public Nullable<int> Int5 { get; set; }
        public Nullable<int> Int6 { get; set; }
        public Nullable<int> Int7 { get; set; }
        public Nullable<int> Int8 { get; set; }
        public Nullable<double> Float1 { get; set; }
        public Nullable<double> Float2 { get; set; }
        public Nullable<double> Float3 { get; set; }
        public Nullable<double> Float4 { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public byte[] VersionStamp { get; set; }
    
        public virtual Operation Operation { get; set; }
        public virtual Parameter Parameter { get; set; }
    }
}
