//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderRelease
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public OrderRelease()
        {
            this.CapacityProfiles = new HashSet<CapacityProfile>();
            this.OrderReleaseDetails = new HashSet<OrderReleaseDetail>();
        }
    
        public int ReleaseID { get; set; }
        public string OrderNo { get; set; }
        public int PartID { get; set; }
        public string PartName { get; set; }
        public Nullable<int> LocationID { get; set; }
        public System.DateTime ReceivedDate { get; set; }
        public System.DateTime DueDate { get; set; }
        public Nullable<System.DateTime> ReleasedDate { get; set; }
        public double OriginalQuantity { get; set; }
        public double PlanQuantity { get; set; }
        public double InventoryQuantity { get; set; }
        public double ProductionQuantity { get; set; }
        public Nullable<System.DateTime> ProductionDate { get; set; }
        public byte Status { get; set; }
        public string Remark { get; set; }
        public string ReservedString1 { get; set; }
        public string ReservedString2 { get; set; }
        public string ReservedString3 { get; set; }
        public string ReservedString4 { get; set; }
        public string ReservedString5 { get; set; }
        public string ReservedString6 { get; set; }
        public string ReservedString7 { get; set; }
        public string ReservedString8 { get; set; }
        public string ReservedString9 { get; set; }
        public string ReservedString10 { get; set; }
        public string ReservedString11 { get; set; }
        public string ReservedString12 { get; set; }
        public Nullable<System.DateTime> ReservedDate1 { get; set; }
        public Nullable<System.DateTime> ReservedDate2 { get; set; }
        public Nullable<System.DateTime> ReservedDate3 { get; set; }
        public Nullable<bool> ReservedFlag1 { get; set; }
        public Nullable<bool> ReservedFlag2 { get; set; }
        public Nullable<bool> ReservedFlag3 { get; set; }
        public Nullable<int> ReservedInt1 { get; set; }
        public Nullable<int> ReservedInt2 { get; set; }
        public Nullable<int> ReservedInt3 { get; set; }
        public Nullable<double> ReservedFloat1 { get; set; }
        public Nullable<double> ReservedFloat2 { get; set; }
        public Nullable<double> ReservedFloat3 { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public byte[] VersionStamp { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CapacityProfile> CapacityProfiles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OrderReleaseDetail> OrderReleaseDetails { get; set; }
    }
}
