//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class part_detail_semicon
    {
        public string unit_id { get; set; }
        public string part_num { get; set; }
        public string cust_id { get; set; }
        public string packagelc { get; set; }
        public string package { get; set; }
        public string leadcount { get; set; }
        public string padsize { get; set; }
        public string device { get; set; }
        public string pkg_dimension { get; set; }
        public string grp { get; set; }
        public string exception_flag { get; set; }
        public string route_id { get; set; }
        public string remark { get; set; }
        public string cust_id_erp { get; set; }
        public string bodysize { get; set; }
        public string applyfor { get; set; }
        public string mold_compound_id { get; set; }
        public string mark_instruction_id { get; set; }
        public string lf_part_id { get; set; }
        public Nullable<System.DateTime> updatedatetime { get; set; }
        public string gold_content { get; set; }
        public string ends_used { get; set; }
        public string hooks_used { get; set; }
        public string alt_ends_used { get; set; }
        public string alt_hooks_used { get; set; }
        public string earring_ends { get; set; }
        public Nullable<int> safety_stock { get; set; }
    }
}
