//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProductRoute
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProductRoute()
        {
            this.ProductRouteStatus = new HashSet<ProductRouteStatu>();
        }
    
        public int ProductRouteId { get; set; }
        public string ProductRouteName { get; set; }
        public int Type { get; set; }
        public int CustomerId { get; set; }
        public int ProductId { get; set; }
        public int RouteId { get; set; }
        public byte Status { get; set; }
        public string Comment { get; set; }
        public string Remarks { get; set; }
        public Nullable<int> Version { get; set; }
        public bool IsActive { get; set; }
        public Nullable<bool> IsDefault { get; set; }
        public string String1 { get; set; }
        public string String2 { get; set; }
        public Nullable<int> Int1 { get; set; }
        public Nullable<int> Int2 { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public byte[] VersionStamp { get; set; }
    
        public virtual Route Route { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProductRouteStatu> ProductRouteStatus { get; set; }
    }
}
