//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteOperation
    {
        public int RouteOperationId { get; set; }
        public int RouteId { get; set; }
        public Nullable<int> OperationId { get; set; }
        public Nullable<int> SubrouteId { get; set; }
        public Nullable<int> Sequence { get; set; }
        public Nullable<int> DefaultResourceID { get; set; }
        public string Instruction { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public byte[] VersionStamp { get; set; }
    
        public virtual Operation Operation { get; set; }
        public virtual Route Route { get; set; }
        public virtual Route Route1 { get; set; }
    }
}
