//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteDetAll
    {
        public int RouteId { get; set; }
        public string ctrcode { get; set; }
        public string maccode { get; set; }
        public Nullable<int> opseq { get; set; }
        public string MacType { get; set; }
    }
}
