//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class RouteMas1
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string remark { get; set; }
        public string UnitID { get; set; }
        public byte Type { get; set; }
        public Nullable<int> Version { get; set; }
    }
}
