//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class shift_det
    {
        public string shift_code { get; set; }
        public short beg_time { get; set; }
        public short end_time { get; set; }
        public string team_id { get; set; }
        public string description { get; set; }
    }
}
