//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class user_det1
    {
        public string login_id { get; set; }
        public string user_name { get; set; }
        public string password { get; set; }
        public string user_title { get; set; }
        public string user_grp { get; set; }
    }
}
