//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class View_TS_WorkOrder
    {
        public int PPID { get; set; }
        public string status { get; set; }
        public string WOID { get; set; }
        public string PartID { get; set; }
        public Nullable<int> ReleaseProdQty { get; set; }
        public string ToolDescription { get; set; }
        public System.DateTime RequestedDeliveryDate { get; set; }
        public Nullable<System.DateTime> ReleasedDate { get; set; }
        public string OrderType { get; set; }
        public string ID { get; set; }
    }
}
