//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderAssembly
    {
        public int AssyWO { get; set; }
        public int ComponentWO { get; set; }
        public Nullable<double> QtyPer { get; set; }
        public Nullable<int> Level { get; set; }
    }
}
