//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class working_rate_except1
    {
        public string part_num { get; set; }
        public int route_id { get; set; }
        public string WOID { get; set; }
        public int seq_no { get; set; }
        public string ctr_code { get; set; }
        public string mc_code { get; set; }
        public Nullable<int> UoM { get; set; }
        public string prod_unit { get; set; }
    }
}
