//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderMaster
    {
        public int ID { get; set; }
        public string Location { get; set; }
        public string Customer { get; set; }
        public string PartNo { get; set; }
        public int Qty { get; set; }
        public int ToStockQty { get; set; }
        public int InvQty1 { get; set; }
        public int InvQty2 { get; set; }
        public int BalQty { get; set; }
        public string OrderType { get; set; }
        public System.DateTime IssueDate { get; set; }
        public System.DateTime DeliveryDate { get; set; }
        public string Status { get; set; }
        public string Remark { get; set; }
        public Nullable<int> RouteID { get; set; }
        public string DrawingStatus { get; set; }
        public string MaterialGrade { get; set; }
        public string MaterialSupplier { get; set; }
        public Nullable<System.DateTime> CreatedDate { get; set; }
        public string UserID { get; set; }
        public string drawing1 { get; set; }
        public string drawing2 { get; set; }
        public string drawing3 { get; set; }
        public string drawing4 { get; set; }
        public Nullable<int> MinQty { get; set; }
        public Nullable<int> MaxQty { get; set; }
        public string FGDimension1 { get; set; }
        public string FGDimension2 { get; set; }
        public string FGDimension3 { get; set; }
    }
}
