//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderAdjustment
    {
        public int WorkOrderAjustmentID { get; set; }
        public int SalesOrderAdjustID { get; set; }
        public int WorkOrderID { get; set; }
        public double PlannedQty { get; set; }
        public double ReducedQty { get; set; }
        public double BalanceQty { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public byte[] VersionStamp { get; set; }
    
        public virtual SalesOrderAdjustment SalesOrderAdjustment { get; set; }
    }
}
