//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderInfo
    {
        public string WOID { get; set; }
        public string CreatedBy { get; set; }
        public string PONumber { get; set; }
        public string PartNum { get; set; }
        public string FGDimension { get; set; }
        public string Description { get; set; }
        public string Remark { get; set; }
        public Nullable<System.DateTime> CommittedDeliveryDate { get; set; }
        public System.DateTime RequestedDeliveryDate { get; set; }
        public Nullable<int> LineNumber { get; set; }
    }
}
