//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.SIMAPS_MOM
{
    using System;
    using System.Collections.Generic;
    
    public partial class WorkOrderMaterial1
    {
        public int WorkOrderMaterialId { get; set; }
        public int WorkOrderId { get; set; }
        public int MaterialId { get; set; }
        public int UnitMeasureID { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }
        public Nullable<bool> Availability { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public System.DateTime ModifiedOn { get; set; }
        public byte[] VersionStamp { get; set; }
        public Nullable<double> Quantity { get; set; }
        public Nullable<double> Ratio { get; set; }
    
        public virtual WorkOrder WorkOrder { get; set; }
        public virtual Item Item { get; set; }
    }
}
