//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_ChildWorkOrder
    {
        public string ParentWOID { get; set; }
        public string ChildWOID { get; set; }
        public int RouteID { get; set; }
        public int ProcOPseq { get; set; }
        public string Type { get; set; }
    }
}
