//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_ExStatus
    {
        public int ID { get; set; }
        public string WOID { get; set; }
        public int ProcOpSeq { get; set; }
        public int ExStatus { get; set; }
        public System.DateTime UpdatedDate { get; set; }
        public string OperatorID { get; set; }
        public string OperatorName { get; set; }
        public string Reason { get; set; }
    }
}
