//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_Lock
    {
        public string WOID { get; set; }
        public string LoginName { get; set; }
        public string LoginID { get; set; }
        public System.DateTime DateTime { get; set; }
        public string MacAddress { get; set; }
    }
}
