//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_MacAddress
    {
        public string MACAddress { get; set; }
        public string Login { get; set; }
        public string Logout { get; set; }
        public System.DateTime LoginDate { get; set; }
        public Nullable<System.DateTime> LogoutDate { get; set; }
    }
}
