//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_Scrap
    {
        public string WOID { get; set; }
        public string WorkCenter { get; set; }
        public int RouteID { get; set; }
        public int OpSeq { get; set; }
        public int ProcOpSeq { get; set; }
        public int ScrapQty { get; set; }
        public System.DateTime ScrapDate { get; set; }
        public string ScrapType { get; set; }
        public string UserID { get; set; }
        public string UserName { get; set; }
        public string Remark { get; set; }
        public string Status { get; set; }
        public string AlertStatus { get; set; }
        public string ApprovedID { get; set; }
        public string ApprovedName { get; set; }
    
        public virtual TS_WorkOrder TS_WorkOrder { get; set; }
    }
}
