//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestTemplate.Repository.EntityFramework.DBContexts.Test
{
    using System;
    using System.Collections.Generic;
    
    public partial class TS_WODispatchBand
    {
        public string WOID { get; set; }
        public int RouteID { get; set; }
        public string McID { get; set; }
        public string WorkCenter { get; set; }
        public int ProcOpSeq { get; set; }
        public int ReleasedProdQty { get; set; }
        public System.DateTime RequestedDeliveryDate { get; set; }
        public Nullable<int> TotalRemainingProcOpSeq { get; set; }
        public Nullable<decimal> SRPTDuration { get; set; }
        public Nullable<int> EDDBand { get; set; }
        public Nullable<int> SRPTBand { get; set; }
        public Nullable<System.DateTime> BandDate { get; set; }
    }
}
